version: "3.8"
services:

  # Job Service & MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      - MONGO_INITDB_DATABASE=job
    volumes:
      - ./job-service/src/main/resources/data/init.js:/docker-entrypoint-initdb.d/init.js

  spring-app:
    build:
      context: ./demo
      dockerfile: Dockerfile
    container_name: spring-app
    ports:
      - "8016:8016"
    profiles:
      - app
    depends_on:
      - mongodb
    environment: 
      - spring.mongodb.uri=mongodb://mahir:1234@mongodb:27017/job
      - spring.mongodb.database=job

  # Candidate Service & MongoDB
  candidate-mongo:
    image: mongo:latest
    container_name: candidate-mongo
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_DATABASE=candidate
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123
    volumes:
      - ./candidate-service/src/main/resources/data/init.js:/docker-entrypoint-initdb.d/init.js

  candidate-app:
    build:
      context: ./candidate-service
      dockerfile: Dockerfile
    container_name: candidate-app
    ports:
      - "8013:8013" 
    profiles:
      - app
    depends_on:
      - candidate-mongo
      - mockserver
    environment:
      - spring.data.mongodb.uri=mongodb://admin:123@candidate-mongo:27017/candidate
      - job.service.url=http://mockserver:1080
      - spring.mongodb.database=candidate

  # MockServer
  mockserver:
    image: mockserver/mockserver:7.4.0
    container_name: mockserver
    ports:
      - "1080:1080"
    environment:
      - MOCKSERVER_MAX_EXPECTATIONS=100
      - MOCKSERVER_MAX_HEADER_SIZE=8192
      - MOCKSERVER_INITIALIZATION_JSON_PATH=/config/init.json
    volumes:
      - ./demo/data/init.json:/config/init.json