events {
    worker_connections 1024; # maksimum istek sayısı aynı anda !
}

http { # http istekleri icin
    server {
        listen 8080; # Konteyner içi dinlenecek port (docker-compose'daki 8086:8080 ayarı için)

        location /api/jobs/ { # nginx servise 
           proxy_pass http://job-service:8012/jobs/; # eger job-service port degistirirse burayı da degistir ! 
        }

        location /api/candidate {
            proxy_pass http://candidate-service:8013/candidate; # eger candidate-service port degistirirse burayı da degistir ! 
        }
        location / { # locationda olmayan diger tum requestleri yakalar !
            root /usr/share/nginx/html; # bu yol girilince static dosyaları hangi klasorde arıyacagını soyler root !
            index index.html; # index bu klasor acılınca varsayılan olarak hangi dosyayı arayacagını soyler !
        }
    }
}